name: Snapshot

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    name: Version
    runs-on: ubuntu-slim
    outputs:
      full_desc: ${{ steps.version.outputs.full_desc }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Version
      id: version
      shell: bash
      run: |
        full_desc=$(git describe --long --tags --match 'wineland-*' --match 'cachyos-wineland-*')
        echo "full_desc=${full_desc#cachyos-}" >> "$GITHUB_OUTPUT"

  build:
    name: Build
    needs: version
    uses: ./.github/workflows/_job_build.yml
    with:
      name: proton-${{ needs.version.outputs.full_desc }}-x86_64
      cflags: -O3 -march=nocona -mtune=core-avx2
      rustflags: -Copt-level=3 -Ctarget-cpu=nocona
      configure: --enable-ccache
      continue: true

  test:
    name: Test
    needs: [version, build]
    uses: ./.github/workflows/_job_test.yml
    with:
      name: proton-${{ needs.version.outputs.full_desc }}-x86_64
      continue: true
